---
- name: "RedHat | Install wazuh-agent"
  ansible.builtin.include_tasks: "setup-{{ ansible_facts.os_family | lower }}.yml"

- name: "Start wazuh-agent"
  ansible.builtin.service:
    name: wazuh-agent
    state: started
    enabled: true
  when:
    - ansible_facts.os_family != "Windows"
    - not wazuh_agent_dl_only|bool
