---
- name: "RHEL10 | Install requierements"
  ansible.builtin.dnf:
    name: ["gnupg2"]
    state: present
  become: true
  register: __pkg_result
  retries: 12
  delay: 10
  until: __pkg_result is success
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '10'

- name: "Redhat | Import a key from a url"
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.wazuh.com/key/GPG-KEY-WAZUH

- name: "Redhat | Copy repo informations"
  ansible.builtin.copy:
    dest: /etc/yum.repos.d/wazuh.repo
    content: |
      [wazuh_repo]
      gpgcheck=1
      gpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH
      enabled=1
      name=Wazuh repository
      baseurl=https://packages.wazuh.com/{{ wazuh_version }}/yum/
      protect=1
    mode: "0644"

- name: "Redhat | Uninstall wazuh-agent package"
  ansible.builtin.dnf:
    name: "wazuh-agent"
    state: absent
  register: __pkg_result
  retries: 12
  delay: 10
  until: __pkg_result is success
  when: wazuh_agent_reinstall|bool

- name: "Redhat | Delete configuration folder"
  ansible.builtin.file:
    path: "/var/ossec"
    state: absent
  when: wazuh_agent_reinstall|bool

- name: "Redhat | Install wazuh-agent package"
  ansible.builtin.dnf:
    name: wazuh-agent
    state: present
  register: __pkg_result
  retries: 12
  delay: 10
  until: __pkg_result is success
  environment:
    WAZUH_MANAGER: "{{ wazuh_manager_ip }}"
    WAZUH_MANAGER_PORT: "{{ wazuh_manager_port }}"
    WAZUH_PROTOCOL: "{{ wazuh_manager_protocol }}"
    WAZUH_REGISTRATION_SERVER: "{{ wazuh_registration_server }}"
    WAZUH_REGISTRATION_PORT: "{{ wazuh_registration_port }}"
    WAZUH_REGISTRATION_PASSWORD: "{{ wazuh_registration_password }}"
    WAZUH_KEEP_ALIVE_INTERVAL: "{{ wazuh_keep_alive_interval }}"
    WAZUH_TIME_RECONNECT: "{{ wazuh_time_reconnect }}"
    WAZUH_REGISTRATION_CA: "{{ wazuh_registration_ca_path }}"
    WAZUH_REGISTRATION_CERTIFICATE: "{{ wazuh_registration_certificate_path }}"
    WAZUH_REGISTRATION_KEY: "{{ wazuh_registration_key_path }}"
    WAZUH_AGENT_NAME: "{{ wazuh_agent_name }}"
    WAZUH_AGENT_GROUP: "{{ wazuh_agent_group }}"
    ENROLLMENT_DELAY: "{{ wazuh_enrollment_delay }}"
  when: not wazuh_agent_dl_only | bool

- name: "Redhat | Install yum-downloadonly"
  ansible.builtin.dnf:
    name: yum-downloadonly
    state: present
  register: __pkg_result
  retries: 12
  delay: 10
  until: __pkg_result is success
  when: wazuh_agent_dl_only | bool

- name: "Redhat | Download only wazuh-agent package"
  ansible.builtin.command: yum install --downloadonly wazuh-agent
  changed_when: false
  when: wazuh_agent_dl_only | bool
